In [2]:
import numpy as np

In [3]:
l = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(l)
print(a)
print(b)

[1, 2, 3, 4, 5]
[15  8 13  5  1]
[ 3  3 16 18  8]


In [4]:
# iteration is needed to perform operations on the elements of list

l = [i + 1 for i in l]
l

[2, 3, 4, 5, 6]

In [5]:
# any operation can be done directly on individual or multiple arrays

a = a + 1
print(a)

g = a ** b
print(g)

[16  9 14  6  2]
[      4096        729 2105606144 1159987200        256]


In [6]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[16  9 14  6  2]
47
9.4
2
4
16
0


In [7]:
a[2] = 0
a[3] = 0
print(a)
print(b)

[16  9  0  0  2]
[ 3  3 16 18  8]


In [8]:
a < b

array([False, False,  True,  True,  True])

In [5]:
# mathematical operations on a 2D list

l1_2d = [[(3 * i) + j for j in range(1, 4)] for i in range(3)]
arr1_2d = np.array(l1_2d)

l2_2d = [[(3 * i) + j for j in range(1, 4)] for i in range(3)]
arr2_2d = np.array(l2_2d)

print(arr2_2d)
print()
print(arr1_2d)
print()

print(arr1_2d @ arr2_2d) # Matrix Multiplication

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
