In [2]:
import numpy as np

In [3]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
[ 1  8 16 11 10  6 13 10]


In [3]:
# Boolean operation on 1D lists
# bool is working as index (here only) where we got True as result

bool = b > 10
print(type(bool))
print(bool)
new = b[bool]
print(new)

<class 'numpy.ndarray'>
[ True  True  True  True  True  True False  True]
[17 12 19 12 17 14 15]


In [4]:
new = b[(b > 10) & (b < 15)]
new

array([12, 12, 14])

In [5]:
print(b)

[17 12 19 12 17 14  9 15]


In [6]:
d = b
d[d > 12]  = 56
print(d)

[56 12 56 12 56 56  9 56]


In [7]:
print(np.where(d == 56))

(array([0, 2, 4, 5, 7], dtype=int64),)


In [8]:
# Q | to print the element of a of index where b has value 56

ind = np.where(d == 11)
print(ind)
print(a[ind])

(array([], dtype=int64),)
[]


In [9]:
# Boolean operation on 2D lists

a = np.random.randint(1, 30, (5, 6))
a

array([[ 7, 27,  2, 12, 23,  5],
       [ 9,  9,  3, 19, 10, 13],
       [19, 18, 14,  9, 12, 18],
       [22, 22, 19, 22, 11,  1],
       [15, 15,  5, 13, 10, 13]])

In [10]:
bool = a > 20
print(bool)

[[False  True False False  True False]
 [False False False False False False]
 [False False False False False False]
 [ True  True False  True False False]
 [False False False False False False]]


In [11]:
ans = a[bool]
ans

array([27, 23, 22, 22, 22])

In [12]:
b = a
b

array([[ 7, 27,  2, 12, 23,  5],
       [ 9,  9,  3, 19, 10, 13],
       [19, 18, 14,  9, 12, 18],
       [22, 22, 19, 22, 11,  1],
       [15, 15,  5, 13, 10, 13]])

In [13]:
b[bool] = 100
b

array([[  7, 100,   2,  12, 100,   5],
       [  9,   9,   3,  19,  10,  13],
       [ 19,  18,  14,   9,  12,  18],
       [100, 100,  19, 100,  11,   1],
       [ 15,  15,   5,  13,  10,  13]])

In [14]:
c = np.random.randint(1, 10, (2, 2))
c

array([[2, 9],
       [8, 5]])

In [15]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [16]:
# in case of boolean arrays they must be of same shape as of original array from which we want to extract data

# print(c[c_bool])

In [17]:
print(b)

[[  7 100   2  12 100   5]
 [  9   9   3  19  10  13]
 [ 19  18  14   9  12  18]
 [100 100  19 100  11   1]
 [ 15  15   5  13  10  13]]


In [18]:
bool_arr = b[:, 2] == 100
bool_arr

array([False, False, False, False, False])

In [19]:
b[bool_arr, 2] = 101

# bool_arr implies the row on which I have to work
# 2 represents the column on which I have to work

b

array([[  7, 100,   2,  12, 100,   5],
       [  9,   9,   3,  19,  10,  13],
       [ 19,  18,  14,   9,  12,  18],
       [100, 100,  19, 100,  11,   1],
       [ 15,  15,   5,  13,  10,  13]])

In [22]:
# Logical Operations

In [45]:
import numpy as np

In [46]:
a1 = np.random.randint(1, 20, 5)
a2 = np.random.randint(1, 20, 5)

In [47]:
a1

array([ 8,  3, 16, 14,  9])

In [48]:
a2

array([13,  9, 15, 13,  4])

In [49]:
np.logical_or(a1, a2)

array([ True,  True,  True,  True,  True])

In [50]:
np.logical_and(a1, a2)

array([ True,  True,  True,  True,  True])

In [51]:
np.logical_not(a1)

array([False, False, False, False, False])

In [52]:
a1 & a2

array([ 8,  1,  0, 12,  0])

In [53]:
a1 | a2

array([13, 11, 31, 15, 13])

In [54]:
~ a1

array([ -9,  -4, -17, -15, -10])