In [1]:
import numpy as np

In [2]:
# mathematical operations are compatiable when m*n is same or one of m*n (m or n) is same

a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3))

print(a)
print(b)

[[7 4 4]
 [3 8 1]
 [6 7 3]]
[4 7 2]


In [3]:
print(a - b)

[[ 3 -3  2]
 [-1  1 -1]
 [ 2  0  1]]


In [4]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (2, 3))

print(a)
print(b)

[[6 2]
 [6 6]
 [6 6]]
[[8 2 2]
 [9 8 1]]


In [5]:
b = np.transpose(b)
print(b)
ans = a - b
print(ans)

[[8 9]
 [2 8]
 [2 1]]
[[-2 -7]
 [ 4 -2]
 [ 4  5]]


In [6]:
# investigate resize and reshape functions

In [7]:
a = np.random.randint(1, 10, (4, 3))
b = np.random.randint(1, 10, (3, 5))

print(a)
print(b)

[[1 8 8]
 [8 2 6]
 [3 7 4]
 [4 6 5]]
[[2 5 8 2 7]
 [3 3 4 4 9]
 [4 9 4 3 5]]


In [8]:
d = np.resize(b, (6, 2))
d
# resize can convert into any order irrespective of no. of elements

array([[2, 5],
       [8, 2],
       [7, 3],
       [3, 4],
       [4, 9],
       [4, 9]])

In [9]:
new = np.reshape(a, (6, 2))
new
# reshape can only be done in such a way so that the no. of elements doesn't change

array([[1, 8],
       [8, 8],
       [2, 6],
       [3, 7],
       [4, 4],
       [6, 5]])